version: '3'

volumes:
  emailer_local_postgres_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./Dockerfile
    image: emailer_local_django
    container_name: emailer_local_django
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - .:/app:z
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: postgres:15.2
    container_name: emailer_local_postgres
    volumes:
      - emailer_local_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.11.11
    container_name: emailer_local_rabbitmq

  celeryworker:
    <<: *django
    image: emailer_local_celeryworker
    container_name: emailer_local_celeryworker
    depends_on:
      - rabbitmq
      - postgres
    ports: []
    command: /start-celeryworker
