# Generated by Django 4.1.7 on 2023-03-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=128, verbose_name='subject')),
                ('body', models.TextField(verbose_name='body')),
            ],
            options={
                'verbose_name': 'email',
                'verbose_name_plural': 'emails',
            },
        ),
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='recipient email')),
                ('sent_date', models.DateTimeField(auto_now_add=True, verbose_name='email sent date')),
                ('read_date', models.DateTimeField(blank=True, null=True, verbose_name='email read date')),
            ],
            options={
                'verbose_name': 'email recipient',
                'verbose_name_plural': 'emails recipients',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=56, verbose_name='template name')),
                ('template', models.TextField()),
            ],
            options={
                'verbose_name': 'email template',
                'verbose_name_plural': 'emaiil templates',
            },
        ),
    ]
