# Generated by Django 4.1.7 on 2023-03-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_emailtemplate_options_alter_email_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecipient',
            name='sent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='email sent date'),
        ),
    ]
