# Generated by Django 4.1.7 on 2023-03-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_alter_emailrecipient_sent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecipient',
            name='failed_count',
            field=models.IntegerField(default=0),
        ),
    ]
