# Generated by Django 4.1.7 on 2023-03-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_emailrecipient_failed_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='send_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
